### ISSUE TITLE
AudioRecorder does not work with JupyterLab

### ISSUE THREAD

**Issue by tillfalko** [maartenbreddels/ipywebrtc#115]
(Jypterlab Version: 3.4.8)
### The Issue
![image](https://user-images.githubusercontent.com/62334868/197250684-4ab83d87-8a7e-40d2-9620-0d478cebe2ce.png)

The exact same code works with Jupyter notebooks.
### Errror Logs
The full error message is:
```
[Open Browser Console for more detailed log - Double click to close this message]
Failed to load model class 'AudioRecorderModel' from module 'jupyter-webrtc'
Error: No version of module jupyter-webrtc is registered
    at f.loadClass (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74856)
    at f.loadModelClass (http://localhost:8888/static/lab/4416.9d6d0a2f3f9ed5d7b141.js?v=9d6d0a2f3f9ed5d7b141:1:11350)
    at f._make_model (http://localhost:8888/static/lab/4416.9d6d0a2f3f9ed5d7b141.js?v=9d6d0a2f3f9ed5d7b141:1:9238)
    at f.new_model (http://localhost:8888/static/lab/4416.9d6d0a2f3f9ed5d7b141.js?v=9d6d0a2f3f9ed5d7b141:1:6735)
    at f.handle_comm_open (http://localhost:8888/static/lab/4416.9d6d0a2f3f9ed5d7b141.js?v=9d6d0a2f3f9ed5d7b141:1:5426)
    at _handleCommOpen (http://localhost:8888/lab/extensions/@jupyter-widgets/jupyterlab-manager/static/134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73393)
    at b._handleCommOpen (http://localhost:8888/static/lab/jlab_core.152fabb1175be11f3bae.js?v=152fabb1175be11f3bae:2:996724)
    at async b._handleMessage (http://localhost:8888/static/lab/jlab_core.152fabb1175be11f3bae.js?v=152fabb1175be11f3bae:2:998714)
```

The error messages in the dev console:
```
Error: widget model not found
    at f.get_model (manager-base.js:128:19)
    at w.renderModel (134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:72019)
renderModel @ 134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1


manager-base.js:575 
        
Error: No version of module jupyter-webrtc is registered
    at f.loadClass (134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:74856)
    at f.loadModelClass (manager-base.js:570:34)
    at f._make_model (manager-base.js:402:36)
    at f.new_model (manager-base.js:245:35)
    at f.handle_comm_open (manager-base.js:155:21)
    at _handleCommOpen (134.bcbea9feb6e7c4da7530.js?v=bcbea9feb6e7c4da7530:1:73393)
    at b._handleCommOpen (default.js:1095:19)
    at async b._handleMessage (default.js:1262:43)
```

### How to (hopefully) reproduce
1. Open test.ipynb with jupyterlab.
2. Create a cell with the following code.
```python
from ipywebrtc import AudioRecorder, CameraStream
camera = CameraStream(constraints={'audio': True,'video':False})
recorder = AudioRecorder(stream=camera)
recorder
```
3. Run the cell.

### What I've tried
```bash
jupyter labextension install jupyter-webrtc
jupyter labextension install js
jupyter labextension install @jupyter-widgets/jupyterlab-manager
```

`jupyter labextension list` shows `jupyter-webrtc v0.6.0 enabled OK`

In JupyterLab itself jupyter-webrtc is listed under 'installed' in the Extension Manager.

### Almost certainly related
https://github.com/maartenbreddels/ipywebrtc/issues/83
https://github.com/maartenbreddels/ipywebrtc/issues/101
https://github.com/maartenbreddels/ipywebrtc/issues/91

**Comment by vipcxj** [comment]
Any news? The same issue.

**Comment by maartenbreddels** [comment]
I've checked it, and it should be working. What could have happened, is that you have a different kernel and jupyter lab environment. If so, also install ipywebrtc in your jupyter lab environment.

**Comment by kizunasunhy** [comment]
I got the reason! It's because the environment you launch the jupyter lab and the kernel environment is different! Say you have 2 conda envs: env1 and env2, then you should launch jupyter and use the kernel both in env1 or env2. That will fix this problem.
![image](https://github.com/maartenbreddels/ipywebrtc/assets/24692121/b9c5e2af-356e-4678-af13-51107244dd44)
